"""create user roles

Revision ID: af80cac07743
Revises: 2b77b490b4b7
Create Date: 2022-02-13 18:51:04.072606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af80cac07743'
down_revision = '2b77b490b4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
